<?php

function test() {
  try {
    throw new Exception(('Ma seconde exception'));
  echo "Je continue";
  } catch (Exception $exception) {
    throw new Exception(('Ma troisiÃ¨me exception'));

    die($exception->getMessage());
  }

  throw new Exception(('Mon exception depuis une fonction'));
}

try {
//  test();

//  echo "Je continue";
} catch (Exception $exception) {
//  die($exception->getMessage());
}

try {
  try {
    throw new Exception('Une premiÃ¨re exception');
  } catch (Exception $e) {
    try {
    } catch (Exception $e) {
      throw new Exception('Une seconde exception');
    }
    throw new Exception('Une troisiÃ¨me exception');
  }
  throw new Exception('Une quatriÃ¨me exception');
} catch (Exception $e) {
  echo $e->getMessage();
}